apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: kubernetes-network
spec:
  serviceAccountName: my-service-account
  containers:
  - name: kubectl
    image: bitnami/kubectl
    command: ["sleep", "3600"]